---
- hosts: node01
  become: yes
  name: Installing apache2 on node01
  tasks:
    - name: Install apache2
      apt:
        update_cache: yes
        name: apache2
        state: latest
- hosts: node02
  become: yes
  name: Installing nginx on node02
  tasks:
    - name: installing nginx
      apt:
        update_cache: yes
        name: nginx
        state: latest
  vars:
    ansible_ssh_user: jenkins
    ansible_ssh_pass: "your_jenkins_password"
  
